---
- name: Manage client device registrations
  delegate_to: "{{ librenms_device_delegate }}"
  block:

    - name: Filter device definitions
      ansible.builtin.set_fact:
        librenms_devices_enabled: "{{ librenms_device_list | difference(_devices_absent) | difference(_devices_disabled) }}"
        librenms_devices_absent: "{{ _devices_absent }}"
        librenms_devices_disabled: "{{ _devices_disabled }}"
        librenms_devices_v2: "{{ _devices_v2 | difference(_devices_absent) }}"
        librenms_devices_v3: "{{ _devices_v3 | difference(_devices_absent) }}"
      vars:
        _devices_state: "{{ librenms_device_list | selectattr('state', 'defined') }}"
        _devices_disabled: "{{ _devices_state | selectattr('state', 'equalto', 'disabled') }}"
        _devices_absent: "{{ _devices_state | selectattr('state', 'equalto', 'absent') }}"
        _devices_versioned: "{{ librenms_device_list | selectattr('version', 'defined') }}"
        _devices_unversioned: "{{ librenms_device_list | rejectattr('version', 'defined') }}"
        _devices_v3: "{{ _devices_versioned | selectattr('version', 'equalto', 'v3') }}"
        _devices_v2: "{{ _devices_unversioned + (_devices_versioned | rejectattr('version', 'equalto', 'v3')) }}"

    - name: Query librenms devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices?type=all"
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        return_content: true
      register: _librenms_devices
      no_log: "{{ librenms_nolog }}"

    - name: Map librenms registrations
      ansible.builtin.set_fact:
        librenms_hostnames: "{{ _librenms_devices.json.devices | map(attribute='hostname') | list }}"
      no_log: "{{ librenms_nolog }}"

    - name: Disable librenms devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices/{{ item.hostname }}"
        method: PATCH
        body_format: json
        body:
          field:
            - disabled
          data:
            - 1
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
      loop: "{{ librenms_devices_disabled }}"
      when: item.state | default('present') == 'disabled'
      no_log: "{{ librenms_nolog }}"

    - name: Remove absent librenms devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices/{{ item.hostname }}"
        method: DELETE
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
      when:
        - item.hostname in librenms_hostnames
        - item.state | default('present') == 'absent'
      loop: "{{ librenms_devices_absent }}"
      no_log: "{{ librenms_nolog }}"

    - name: Create librenms v2c devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices"
        method: POST
        body_format: json
        body:
          hostname: "{{ item.hostname }}"
          display: "{{ item.display | default(item.hostname) }}"
          version: "{{ item.version | default(librenms_client_snmp_version) }}"
          community: "{{ item.community | default(librenms_client_snmp_community) }}"
          port: "{{ item.port | default(librenms_client_snmp_port) }}"
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        validate_certs: false
        status_code:
          - 200
          - 201
      when: not item.hostname in librenms_hostnames
      loop: "{{ librenms_devices_v2 }}"
      no_log: "{{ librenms_nolog }}"

    - name: Update librenms v2c devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices/{{ item.hostname }}"
        method: PATCH
        body_format: json
        body:
          field:
            - display
            - port
            - version
            - community
          data:
            - "{{ item.display | default(item.hostname) }}"
            - "{{ item.port | default(librenms_client_snmp_port) }}"
            - "{{ item.version | default(librenms_client_snmp_version) }}"
            - "{{ item.community | default(librenms_client_snmp_community) }}"
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        validate_certs: false
        status_code:
          - 200
          - 201
      loop: "{{ librenms_devices_v2 }}"
      no_log: "{{ librenms_nolog }}"

    - name: Create librenms v3 devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices"
        method: POST
        body_format: json
        body:
          hostname: "{{ item.hostname }}"
          display: "{{ item.display | default(item.hostname) }}"
          version: "{{ item.version | default(librenms_client_snmp_version) }}"
          port: "{{ item.port | default(librenms_client_snmp_port) }}"
          authlevel: "{{ (item.authlevel | default(librenms_client_snmp_authlevel)) if librenms_client_snmp_version == 'v3' else omit }}"
          authname: "{{ (item.authname | default(librenms_client_snmp_authname)) if librenms_client_snmp_version == 'v3' else omit }}"
          authpass: "{{ (item.authpass | default(librenms_client_snmp_authpass)) if librenms_client_snmp_version == 'v3' else omit }}"
          authalgo: "{{ (item.authalgo | default(librenms_client_snmp_authalgo)) if librenms_client_snmp_version == 'v3' else omit }}"
          cryptopass: "{{ (item.cryptopass | default(librenms_client_snmp_cryptopass)) if librenms_client_snmp_version == 'v3' else omit }}"
          cryptoalgo: "{{ (item.cryptoalgo | default(librenms_client_snmp_cryptoalgo)) if librenms_client_snmp_version == 'v3' else omit }}"
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        validate_certs: false
        status_code:
          - 200
          - 201
      vars:
        _version:
      when: not item.hostname in librenms_hostnames
      loop: "{{ librenms_devices_v3 }}"
      no_log: "{{ librenms_nolog }}"

    - name: Update librenms v3 devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices/{{ item.hostname }}"
        method: PATCH
        body_format: json
        body:
          field:
            - display
            - port
            - version
            - community
          data:
            - "{{ item.display | default(item.hostname) }}"
            - "{{ item.port | default(librenms_client_snmp_port) }}"
            - "{{ item.version | default(librenms_client_snmp_version) }}"
            - "{{ item.community | default(librenms_client_snmp_community) }}"
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        validate_certs: false
        status_code:
          - 200
          - 201
      loop: "{{ librenms_devices_v3 }}"
      no_log: "{{ librenms_nolog }}"

    - name: Rediscover librenms devices
      ansible.builtin.uri:
        url: "{{ librenms_url }}/api/v0/devices/{{ item }}/discover"
        body_format: json
        headers:
          X-Auth-Token: "{{ librenms_api_token }}"
        validate_certs: false
      loop: "{{ librenms_devices_enabled | map(attribute='hostname') }}"
      no_log: "{{ librenms_nolog | default(true) }}"
