---
- name: Deploy server components
  ansible.builtin.include_tasks: server.yml
  when: librenms_server_install | bool

- name: Deploy client components
  ansible.builtin.include_tasks: client.yml
  when: librenms_client_install | bool

- name: Register librenms clients
  ansible.builtin.include_tasks: register.yml
  when: librenms_client_register | bool

- name: Register extra librenms devices
  ansible.builtin.include_tasks: devices.yml
  when: librenms_device_list | length > 0
