---
- name: Deploy client components
  include_tasks: client.yml
  when: librenms_client_install | bool

- name: Register librenms tasks
  include_tasks: register.yml
  when: librenms_client_register | bool

- name: Deploy server components
  include_tasks: server.yml
  when: librenms_server_install | bool
