---
- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
    enabled: true

- name: Restart fpm
  ansible.builtin.service:
    name: "php{{ _librenms_php_version }}-fpm"
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
