---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: server
    image: geerlingguy/docker-${MOLECULE_SERVER_DISTRO:-ubuntu2004}-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
      - NET_RAW
    command: ${MOLECULE_IMAGE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - servers
    published_ports:
      - 8080:80/tcp
  - name: client
    image: geerlingguy/docker-${MOLECULE_CLIENT_DISTRO:-ubuntu2004}-ansible:latest
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    capabilities:
      - SYS_ADMIN
      - NET_RAW
    command: ${MOLECULE_IMAGE_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    groups:
      - clients
    published_ports:
      - 8016:161/udp
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all:
        server_group: servers
        librenms_nolog: false
        librenms_client_snmp_version: v2c
        librenms_client_snmp_community: public
      servers:
        librenms_server_install: true
        librenms_client_register: false
        librenms_root: /opt/librenms
        librenms_user: librenms
        librenms_group: librenms
        librenms_admin_user: admin
        librenms_admin_pass: admin
        librenms_db_user: database
        librenms_db_pass: database
        librenms_db_name: librenms
        librenms_db_host: localhost
      clients:
        librenms_client_snmp_port: 8016
        librenms_client_register: true

verifier:
  name: ansible
