---
- name: Prepare
  hosts: clients
  gather_facts: false
  tasks:
    - name: Replace sudo PAM config to allow passwordless access in container
      ansible.builtin.copy:
        dest: /etc/pam.d/sudo
        content: |
          #%PAM-1.0
          session    include      system-auth
        mode: '0644'
