---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  molecule:
    name: molecule tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - ubuntu2204
          - ubuntu2404
          - debian12
        client:
          - ubuntu2204
          - ubuntu2404
          - debian12
    steps:
      - name: Disable apparmor
        run: |
          set -x
          sudo apt-get install apparmor-profiles
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: "make install requirements test"
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_SCENARIO: default
          MOLECULE_SERVER_DISTRO: ${{ matrix.server }}
          MOLECULE_CLIENT_DISTRO: ${{ matrix.client }}
          MOLECULE_IMAGE_COMMAND: /lib/systemd/systemd
