---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  molecule:
    name: molecule tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - ubuntu2204
          - ubuntu2404
        client:
          - ubuntu2204
          - ubuntu2404
          - debian12
    steps:
      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: >
            just
            --set MOLECULE_SERVER_DISTRO ${{ matrix.server }}
            --set MOLECULE_CLIENT_DISTRO ${{ matrix.client }}
            requirements test
